language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=OneApply,landingpage,logIn,register,high_school manage.py test

after_script:
  - coveralls