# Generated by Django 2.2.6 on 2019-10-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admissions", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="highschoolapplication",
            name="parent_phoneNumber",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="phoneNumber",
            field=models.CharField(max_length=15),
        ),
    ]
