# Generated by Django 2.2.6 on 2019-11-04 06:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("register", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="HighSchoolApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_number", models.CharField(max_length=10)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email_address",
                    models.EmailField(
                        max_length=50,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("parent_name", models.CharField(max_length=100)),
                (
                    "parent_phoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("school", models.CharField(max_length=100)),
                ("program", models.CharField(max_length=100)),
                ("is_draft", models.BooleanField(default=True)),
                ("submitted_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="high_school_app_user",
                        to="register.Student",
                    ),
                ),
            ],
        )
    ]
