# Generated by Django 2.2.6 on 2019-11-04 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("application", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="highschoolapplication",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="high_school_app_school",
                to="high_school.HighSchool",
            ),
        )
    ]
