# Generated by Django 2.2.6 on 2019-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_highschoolapplication_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolapplication',
            name='application_status',
            field=models.IntegerField(default='2'),
        ),
    ]
