# Generated by Django 2.2.6 on 2019-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("application", "0003_auto_20191113_1120")]

    operations = [
        migrations.AlterField(
            model_name="highschoolapplication",
            name="application_status",
            field=models.IntegerField(default=2),
        )
    ]
