# Generated by Django 2.2.6 on 2019-11-25 22:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [("application", "0004_auto_20191113_1300")]

    operations = [
        migrations.AlterField(
            model_name="highschoolapplication",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="application_status",
            field=models.IntegerField(default=2, verbose_name="Application Status"),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="date_of_birth",
            field=models.DateField(verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="email_address",
            field=models.EmailField(
                max_length=50,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email ID",
            ),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="gender",
            field=models.CharField(max_length=15, verbose_name="Gender"),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("4.00")),
                ],
                verbose_name="GPA",
            ),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="parent_name",
            field=models.CharField(max_length=100, verbose_name="Parent/Guardian Name"),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="parent_phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Parent/Guardian Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="high_school.Program",
                verbose_name="Program",
            ),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app_school",
                to="high_school.HighSchool",
                verbose_name="School",
            ),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="submitted_date",
            field=models.DateTimeField(verbose_name="Submitted"),
        ),
    ]
