# Generated by Django 2.2.6 on 2019-11-26 04:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [("application", "0005_auto_20191125_1746")]

    operations = [
        migrations.AlterField(
            model_name="highschoolapplication",
            name="parent_phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Parent/Guardian Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="highschoolapplication",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone Number"
            ),
        ),
    ]
