# Generated by Django 2.2.6 on 2019-11-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("application", "0006_auto_20191112_1922")]

    operations = [
        migrations.RemoveField(
            model_name="highschoolapplication", name="applications_status"
        ),
        migrations.AddField(
            model_name="highschoolapplication",
            name="application_status",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
