# Generated by Django 2.2.6 on 2019-10-10 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.EmailField(max_length=200, null=True, validators=[django.core.validators.EmailValidator()])),
                ('username', models.CharField(max_length=20, null=True)),
                ('current_school', models.CharField(blank=True, max_length=100, null=True)),
                ('borough', models.CharField(choices=[('MN', 'Manhattan'), ('BK', 'Brooklyn'), ('QN', 'Queens'), ('BX', 'The Bronx'), ('SI', 'Staten Island')], max_length=2)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
