# Generated by Django 2.2.6 on 2019-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='borough',
            field=models.CharField(max_length=2),
        ),
    ]
