# Generated by Django 2.2.7 on 2019-11-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_school', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fav_schools',
            field=models.ManyToManyField(blank=True, to='high_school.HighSchool'),
        ),
    ]
