# Generated by Django 2.2.6 on 2019-10-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("register", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="admin_staff",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_school.HighSchool",
            ),
        )
    ]
