# Generated by Django 2.2.6 on 2019-11-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("register", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="admin_staff",
            name="phoneNumber",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="phoneNumber",
            field=models.CharField(max_length=15),
        ),
    ]
