# Generated by Django 2.2.7 on 2019-11-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("register", "0002_student_fav_schools")]

    operations = [
        migrations.AlterModelOptions(
            name="admin_staff", options={"ordering": ["first_name"]}
        ),
        migrations.AlterModelOptions(
            name="student", options={"ordering": ["first_name"]}
        ),
    ]
