# Generated by Django 2.2.6 on 2019-10-29 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("register", "0002_remove_admin_staff_school_id")]

    operations = [
        migrations.AlterField(
            model_name="admin_staff",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="high_school.HighSchool"
            ),
        )
    ]
