# Generated by Django 2.2.7 on 2019-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_school", "0002_auto_20191105_1536"),
        ("register", "0003_auto_20191105_2317"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fav_schools",
            field=models.ManyToManyField(blank=True, to="high_school.HighSchool"),
        )
    ]
