# Generated by Django 2.2.6 on 2019-10-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("register", "0003_auto_20191016_1204")]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=False),
        )
    ]
