# Generated by Django 2.2.6 on 2019-11-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20191113_0205'),
        ('register', '0003_auto_20191112_2340'),
    ]

    operations = [
    ]
