# Generated by Django 2.2.6 on 2019-11-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("register", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="admin_staff", name="phoneNumber"),
        migrations.RemoveField(model_name="student", name="phoneNumber"),
    ]
