# Generated by Django 2.2.6 on 2019-10-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_admin_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_staff',
            name='school_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
