# Generated by Django 2.2.6 on 2019-10-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_admin_staff"),
        ("register", "0004_student_is_active"),
    ]

    operations = []
