# Generated by Django 2.2.6 on 2019-10-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_admin_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_staff',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phoneNumber',
        ),
    ]
