# Generated by Django 2.2.6 on 2019-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("register", "0005_merge_20191023_1130")]

    operations = [
        migrations.AddField(
            model_name="admin_staff",
            name="is_active",
            field=models.BooleanField(default=False),
        )
    ]
