# Generated by Django 2.2.6 on 2019-10-29 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("register", "0005_auto_20191025_2347")]

    operations = [
        migrations.AddField(
            model_name="admin_staff",
            name="phoneNumber",
            field=models.CharField(
                default="(777) 999-1234",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "r'^([0-9]{3}) [0-9]{3}-[0-9]{4}$'"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="phoneNumber",
            field=models.CharField(
                default="777 122 2211",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "r'^([0-9]{3}) [0-9]{3}-[0-9]{4}$'"
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
