# Generated by Django 2.2.6 on 2019-12-11 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("register", "0005_upgrade_password")]

    operations = [
        migrations.AlterField(
            model_name="admin_staff",
            name="email_address",
            field=models.EmailField(
                max_length=200,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email_address",
            field=models.EmailField(
                max_length=200,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
