# Generated by Django 2.2.6 on 2019-10-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_admin_staff_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_staff',
            name='school_id',
            field=models.CharField(max_length=100),
        ),
    ]
