# Generated by Django 2.2.6 on 2019-10-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("register", "0006_admin_staff_is_active")]

    operations = [
        migrations.AddField(
            model_name="admin_staff",
            name="is_verified_employee",
            field=models.BooleanField(default=False),
        )
    ]
