# Generated by Django 2.2.6 on 2019-10-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0006_auto_20191028_2317"),
        ("register", "0006_admin_staff_is_active"),
    ]

    operations = []
