# Generated by Django 2.2.6 on 2019-10-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0007_admin_staff_is_verified_employee"),
        ("register", "0007_merge_20191029_0116"),
    ]

    operations = []
