# Generated by Django 2.2.6 on 2019-10-29 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_admin_staff_is_verified_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_staff',
            name='email_address',
            field=models.EmailField(max_length=200, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='admin_staff',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_address',
            field=models.EmailField(max_length=200, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
