# Generated by Django 2.2.6 on 2019-11-06 04:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("register", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email_address",
                    models.EmailField(
                        max_length=50,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("recommendation", models.TextField()),
                ("submitted_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_recommending",
                        to="register.Student",
                    ),
                ),
            ],
        )
    ]
