# Generated by Django 2.2.6 on 2019-11-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recommendation", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="recommendation",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="submitted_date",
            field=models.DateTimeField(null=True),
        ),
    ]
