# Generated by Django 2.2.6 on 2019-11-26 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recommendation", "0005_auto_20191125_2201")]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="known_length",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(15),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Years",
            ),
        )
    ]
