# Generated by Django 2.2.6 on 2019-10-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high_school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HighSchools',
            new_name='HighSchool',
        ),
    ]
