# Generated by Django 2.2.7 on 2019-11-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("high_school", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="highschool", options={"ordering": ["school_name"]}
        ),
        migrations.AlterModelOptions(name="program", options={"ordering": ["name"]}),
    ]
