# Generated by Django 2.2.6 on 2019-11-10 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("high_school", "0002_auto_20191105_1536")]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("number_of_seats", models.IntegerField(blank=True, null=True)),
                ("offer_rate", models.IntegerField(blank=True, null=True)),
                (
                    "high_school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="high_school.HighSchool",
                    ),
                ),
            ],
        )
    ]
