# Generated by Django 2.2.6 on 2019-10-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("high_school", "0004_auto_20191026_1734")]

    operations = [
        migrations.AddField(
            model_name="highschool",
            name="graduation_rate",
            field=models.FloatField(default=0.0, max_length=5),
            preserve_default=False,
        )
    ]
